config/routes.rb
RaRenewed::Application.routes.draw do
  resources :surfboards

  resources :videos

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'home#index'

  get "home/index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/surfboard.rb
class Surfboard < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :name, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout "end_user"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/surfboards_controller.rb
class SurfboardsController < InheritedResources::Base
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/surfboards_helper.rb
module SurfboardsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<div id="full-width-slider" class="royalSlider heroSlider rsMinW">
  <div class="rsContent">
    <%= image_tag('1.png', :class => 'rsImg') %>
    <div class="infoBlock infoBlockLeftBlack rsABlock rsNoDrag" data-fade-effect="" data-move-offset="10" data-move-effect="bottom" data-speed="200">
      <h4>This is an animated block, add any number of them to any type of slide</h4>
      <p>Put completely anything inside - text, images, inputs, links, buttons.</p>
    </div>
  </div>
  <div class="rsContent">
    <%= image_tag('2.png', :class => 'rsImg') %>
     <div class="infoBlock  rsAbsoluteEl rsNoDrag" data-fade-effect="" data-move-offset="10" data-move-effect="bottom" data-speed="200">
      <h4>This is a static HTML block</h4>
      <p>It's always displayed and not animated by slider.</p>
    </div>
  </div>
 <div class="rsContent">
    <%= image_tag('3.png', :class => 'rsImg') %>
    <div class="infoBlock rsABlock infoBlockLeftBlack rsNoDrag" data-fade-effect="" data-move-offset="10" data-move-effect="bottom" data-speed="200">
      <h4>Touch events are disabled over this text to allow selection</h4>
      <p>You can add this behaviour to any element inside of slide just by adding 'rsNoDrag' CSS class to it.</p>
    </div>
  </div>
  <div class="rsContent">
    <%= image_tag('4.png', :class => 'rsImg') %>
  </div>
</div>

app/views/layouts/_bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RaRenewed" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name + "_action" %>" class='<%= controller_name %> <%= Rails.env %>'>
    <%= yield(:menu) %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="content">
        <%= yield(:content) %>
      </div><!--/content-->

      <footer>
        <p>&copy; Robert August 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Robert August</a>
      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <li><%= link_to "Surfboards", surfboards_path  %></li>
          <li><%= link_to "Video Gallery", videos_path  %></li>
          <li><%= link_to "Accessories", "/"  %></li>
          <li><%= link_to "Blog", "/"  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/end_user.html.erb
<%= content_for(:menu) do %>
  <%= render partial: 'layouts/menu' %>
<% end %>

<%= content_for(:content) do %>
  <%= yield %>
<% end %>

<%= render partial: "layouts/bootstrap" %>

app/views/surfboards/_form.html.erb
<%= simple_form_for(@surfboard) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/surfboards/edit.html.erb
<h1>Editing surfboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @surfboard %> |
<%= link_to 'Back', surfboards_path %>

app/views/surfboards/index.html.erb
<h1>Listing surfboards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surfboards.each do |surfboard| %>
  <tr>
    <td><%= surfboard.name %></td>
    <td><%= link_to 'Show', surfboard %></td>
    <td><%= link_to 'Edit', edit_surfboard_path(surfboard) %></td>
    <td><%= link_to 'Destroy', surfboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Surfboard', new_surfboard_path %>

app/views/surfboards/new.html.erb
<h1>New surfboard</h1>

<%= render 'form' %>

<%= link_to 'Back', surfboards_path %>

app/views/surfboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @surfboard.name %>
</p>


<%= link_to 'Edit', edit_surfboard_path(@surfboard) %> |
<%= link_to 'Back', surfboards_path %>

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="row clearfix">
  <div class="col fwImage">
    <div id="video-gallery" class="royalSlider videoGallery rsDefault">
      <a class="rsImg" data-rsVideo="https://vimeo.com/26323301" href="http://b.vimeocdn.com/ts/174/317/174317046_640.jpg">
        <div class="rsTmb">
          <h5>Endless Summer</h5>
          <p>by RA</p>
        </div>
      </a>

      <a class="rsImg" data-rsVideo="https://vimeo.com/27702618" href="http://b.vimeocdn.com/ts/184/192/184192590_640.jpg">
        <div class="rsTmb">
          <h5>Wefi Surfboards</h5>
          <p>by mark wyatt</p>
        </div>
      </a>

      <div class="rsContent">
        <a class="rsImg" data-rsVideo="https://vimeo.com/36124816" href="http://b.vimeocdn.com/ts/248/526/248526072_640.jpg">
          <div class="rsTmb">
            <h5>Life's Better in Boardshorts short film</h5>
            <p>by Billabong</p>
          </div>
        </a>
        <h3 class="rsABlock sampleBlock">This animated block is here just to show you that you can put anything you want inside each slide.</h3>
      </div>

      <a class="rsImg" data-rsVideo="https://vimeo.com/44253174" href="http://b.vimeocdn.com/ts/307/432/307432227_640.jpg">
        <div class="rsTmb">
          <h5>Globe's Electric Blue Heaven</h5>
          <p>by GLOBE</p>
        </div>
      </a>

      <a class="rsImg" data-rsVideo="https://vimeo.com/18867695" href="http://b.vimeocdn.com/ts/160/715/160715680_640.jpg">
        <div class="rsTmb">
          <h5>Night Surf</h5>
          <p>by Iker Elorrieta</p>
        </div>
      </a>

      <a class="rsImg" data-rsVideo="https://vimeo.com/33001035" href="http://b.vimeocdn.com/ts/225/163/225163711_640.jpg">
        <div class="rsTmb">
          <h5>Maldives Taster 2011</h5>
          <p>by Billabong</p>
        </div>
      </a>

      <a class="rsImg" data-rsVideo="https://vimeo.com/18560206" href="http://b.vimeocdn.com/ts/116/865/116865080_640.jpg">
        <div class="rsTmb">
          <h5>Alana Blanchard</h5>
          <p>by Flicka Mag</p>
        </div>
      </a>

    </div>
  </div>
</div>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @video.name %>
</p>

<p>
  <b>Url:</b>
  <%= @video.url %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>